### PR TITLE
fix(errctx): remove NoteMask, `Notef` should be use instead

### LINKED ISSUE #457: [ErrCtx] NoteMask should take a pass function in parameter according to errgo

### PR DESCRIPTION
**Pull request by curzolapierre**
Fix #457

- [x] Add a changelog entry in `CHANGELOG.md`

### CODE REVIEW

File: errors/errctx.go [hunk 1]
```diff
@@ -28,8 +28,8 @@ func Newf(ctx context.Context, format string, args ...interface{}) error {
 	return ErrCtx{ctx: ctx, err: errgo.Newf(format, args...)}
 }
 
-func NoteMask(ctx context.Context, err error, message string) error {
-	return ErrCtx{ctx: ctx, err: errgo.NoteMask(err, message)}
+func NoteMask(ctx context.Context, err error, message string, pass ...func(error) bool) error {
+	return ErrCtx{ctx: ctx, err: errgo.NoteMask(err, message, pass...)}
 }
```
Comment (EtienneM) [inline errors/errctx.go:33]: Sorry I didn't know about this function but it should not be implemented. We don't use and `*Mask*` function since a loooong time. Any call to a Mask function should be converted to a `Notef` call.
```suggestion
```

File: errors/CHANGELOG.md [hunk 2]
```diff
@@ -2,6 +2,8 @@
 
 ## To be Released
 
+* fix: `NoteMask` is taking a pass function as parameter
```
Comment (EtienneM) [inline errors/CHANGELOG.md:5]: The changelog does not look that good anymore :p

**Review by EtienneM — APPROVED** [review]
