### PR TITLE
fix(otel): Return early if SDK is disabled

### LINKED ISSUE #1279: [otel] If SDK is disabled it should exit earlier, before configuration is loaded

### PR DESCRIPTION
**Pull request by brandon-welsch**
Fix #1279 

- [x] Add a changelog entry in `CHANGELOG.md`

### CODE REVIEW

**Review by briceamen — APPROVED** [review]
LGTM

File: otel/otel.go [hunk 1]
```diff
@@ -34,19 +34,21 @@ type Config struct {
 }
 
 func Init(ctx context.Context) (func(context.Context) error, error) {
+	// If SDK is disabled through env, exit earlier without any error
+	isSDKDisabled := os.Getenv("OTEL_SDK_DISABLED")
+	if isSDKDisabled == "true" {
+		return func(ctx context.Context) error {
+			return nil
```
Comment (curzolapierre) [inline otel/otel.go:41]: **Suggestion**: IMO a log message would be useful here

**Review by curzolapierre — COMMENTED** [review]
**Question**: would we prefer to explicit disable the initialization or more if the required env variables are not set then the service is not init
